### ISSUE TITLE
Add secondary authors

### ISSUE THREAD

**Issue by labkode** [instanto/instanto-public#12]
In every place a publication is listed, the secondary authors should be in the same list, putting the primary author in the first position and secondaries next ordered alphabetically.
Example:
Publication title: Some publication very interesting
Authors: Hugo, Alba, María, Zeta

Where Hugo is the primary and María and Zeta secondaries.

The RESP API should give you the authors in this order, if not please open an issue at https://github.com/instanto/instanto-lib

**Comment by inad9300** [comment]
OK, I did it for the research lines and the scientific publications. I considered it not necessary for the members, since the focus there is the member himself, and there is already a link to see the details of the publications.

About the student works, are there secondary authors in that case? I don't think there are, but I ask just in case.

**Comment by labkode** [comment]
Regarding student works, there is are no secondary authors.
In the other hand, in member detailed view, when listing the publications, we shoudl list two sets.
One a list of publications in which you are the primary author (already implemented) and other with publications you appear as secondary (not sure if it is done).
@inad9300

**Comment by inad9300** [comment]
Not exactly that way, but I think it is. What you can see now is the list of publications with a comment on the right saying if the current member is the "Main author" or a "Co-author" of it. Is it OK like this? Maybe we can re consider the names themselves.

**Comment by labkode** [comment]
I think is ok.
